- name: Register system with Red Hat Subscription Manager
  community.general.redhat_subscription:
    state: present
    username: "{{ rhsm_user }}"
    password: "{{ rhsm_password }}"
    pool_ids: "{{ rhsm_pool_id }}"

- name: Enable required RHSM repositories
  community.general.rhsm_repository:
    name:
      - ansible-automation-platform-2.4-for-rhel-9-x86_64-rpms
    state: enabled

- name: Ensure all packages are updated
  ansible.builtin.dnf:
    name: '*'
    state: latest # noqa package-latest

- name: Ensure all packages are updated
  ansible.builtin.dnf:
    name: 'ansible-automation-platform-installer'
    state: present

- name: Copy inventory for Automation Hub
  ansible.builtin.template:
    src: inventory-hub.j2
    dest: "/opt/ansible-automation-platform/installer/inventory"
    mode: "0755"

- name: Install Automation Hub
  ansible.builtin.shell:
    cmd: ./setup.sh
    chdir: /opt/ansible-automation-platform/installer

- name: Reboot server
  ansible.builtin.reboot:
