- name: Register system with Red Hat Subscription Manager
  community.general.redhat_subscription:
    state: present
    username: "{{ rhsm_user }}"
    password: "{{ rhsm_password }}"
    pool_ids: "{{ rhsm_pool_id }}"

- name: Enable required RHSM repositories
  community.general.rhsm_repository:
    name:
      - ansible-automation-platform-2.2-for-rhel-9-x86_64-rpms
    state: enabled

- name: Ensure all packages are updated
  ansible.builtin.dnf:
    name: '*'
    state: latest # noqa package-latest