- name: Register system with Red Hat Subscription Manager
  community.general.redhat_subscription:
    state: present
    username: "{{ rhsm_user }}"
    password: "{{ rhsm_password }}"
    pool_ids: "{{ rhsm_pool_id }}"

- name: Enable required RHSM repositories
  community.general.rhsm_repository:
    name:
      - ansible-automation-platform-2.2-for-rhel-9-x86_64-rpms
    state: enabled

- name: Ensure all packages are updated
  ansible.builtin.dnf:
    name: '*'
    state: latest # noqa package-latest

- name: Create destination directory
  ansible.builtin.file:
    path: ~/aap2
    state: directory
    mode: 0755

- name: Extract AAP2 setup content
  ansible.builtin.unarchive:
    src: "{{ hostvars['localhost']['product_filename'] }}"
    dest: ~/aap2

- name: Get aap2 folder name
  ansible.builtin.find:
    paths: ~/aap2
    file_type: directory
  register: untar

- name: Copy inventory for controller
  ansible.builtin.template:
    src: inventory-servicecatalog.j2
    dest: "{{ untar.files[0].path }}/inventory"
    mode: 0755

- name: Install Service Catalog
  ansible.builtin.shell:
    cmd: ./setup.sh
    chdir: "{{ untar.files[0].path }}"

- name: Reboot server
  ansible.builtin.reboot:
