---
- name: Include controller setup tasks
  ansible.builtin.import_tasks:
    file: aap2-controller-setup.yml
  when: aap2_setup_controller and inventory_hostname == 'controller'

- name: Include hub setup tasks
  ansible.builtin.import_tasks:
    file: aap2-hub-setup.yml
  when: aap2_setup_hub and inventory_hostname == 'hub'
