- name: Register system with Red Hat Subscription Manager
  community.general.redhat_subscription:
    state: present
    username: "{{ rhsm_user }}"
    password: "{{ rhsm_password }}"
    # pool_ids: "{{ rhsm_pool_id }}"

- name: Enable required RHSM repositories
  community.general.rhsm_repository:
    name:
      - ansible-automation-platform-2.5-for-rhel-9-x86_64-rpms
    state: enabled

- name: Ensure all packages are updated
  ansible.builtin.dnf:
    name: '*'
    state: latest # noqa package-latest

- name: Ensure all packages are updated
  ansible.builtin.dnf:
    name: 'ansible-automation-platform-installer'
    state: present

- name: Copy inventory for Automation Platform
  ansible.builtin.template:
    src: inventory.j2
    dest: "/opt/ansible-automation-platform/installer/inventory"
    mode: "0755"

- name: Configure SSL
  when: aap_configure_ssl
  block:
    - name: Copy CA and certs for SSL configuration
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/ansible-automation-platform/installer/{{ item }}
        mode: "0755"
      loop:
        - "{{ aap_ca }}"

    - name: Copy CA and certs for SSL configuration
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/ansible-automation-platform/installer/{{ item }}
        mode: "0755"
      loop:
        - "{{ aap_controller_cert }}"
        - "{{ aap_controller_key }}"
      when: controller_configure_ssl

    - name: Copy CA and certs for SSL configuration
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/ansible-automation-platform/installer/{{ item }}
        mode: "0755"
      loop:
        - "{{ aap_hub_cert }}"
        - "{{ aap_hub_key }}"
      when: hub_configure_ssl

    - name: Copy CA and certs for SSL configuration
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/ansible-automation-platform/installer/{{ item }}
        mode: "0755"
      loop:
        - "{{ aap_gw_cert }}"
        - "{{ aap_gw_key }}"
      when: gw_configure_ssl

    - name: Copy CA and certs for SSL configuration
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/ansible-automation-platform/installer/{{ item }}
        mode: "0755"
      loop:
        - "{{ aap_eda_cert }}"
        - "{{ aap_eda_key }}"
      when: eda_configure_ssl

- name: Configure Content Signing
  when: aap_configure_content_signing
  block:
    - name: Copy CA and certs for SSL configuration
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/ansible-automation-platform/installer/{{ item }}
        mode: "0755"
      loop:
        - "{{ aap_content_signing_key }}"
        - "{{ aap_content_signing_script }}"

- name: Install Automation Platform
  ansible.builtin.shell:
    cmd: ./setup.sh
    chdir: /opt/ansible-automation-platform/installer

- name: Reboot server
  ansible.builtin.reboot:
