---
# tasks file for role-aap2-setup
- name: Include setup tasks
  ansible.builtin.include_tasks:
    file: aap2-hub-setup.yml

- name: Include controller setup tasks
  ansible.builtin.include_tasks:
    file: aap2-controller-setup.yml
  when: install_controller

- name: Include hub setup tasks
  ansible.builtin.include_tasks:
    file: aap2-hub-setup.yml
  when: install_hub
