- name: Register system with Red Hat Subscription Manager
  community.general.redhat_subscription:
    state: present
    username: "{{ rhsm_user }}"
    password: "{{ rhsm_password }}"

- name: Ensure all packages are updated
  ansible.builtin.dnf:
    name: '*'
    state: latest # noqa package-latest

- name: Configure package for RPM setup
  when: 
    - aap_setup_rpm is defined
    - aap_setup_rpm
  block:
    - name: Enable required RHSM repositories
      community.general.rhsm_repository:
        name:
          - ansible-automation-platform-2.5-for-rhel-9-x86_64-rpms
        state: enabled

    - name: Install AAP2 RPM
      ansible.builtin.dnf:
        name: 'ansible-automation-platform-installer'
        state: present

    - name: Copy inventory for Automation Platform
      ansible.builtin.template:
        src: inventory_rpm.j2
        dest: "/opt/ansible-automation-platform/installer/inventory"
        mode: "0755"

- name: Configure system for container setup
  when:
    - aap_setup_container is defined 
    - aap_setup_container  
  block:
    - name: Ensure required packages are present
      ansible.builtin.dnf:
        name: 
          - wget 
          - git-core 
          - rsync 
          - vim
          - ansible-core
          
    - name: Copy inventory for Automation Platform
      when: aap_setup_single_node is not defined or not aap_setup_single_node
      ansible.builtin.template:
        src: inventory_container.j2
        dest: "/opt/ansible-automation-platform/installer/inventory"
        mode: "0755"    

    - name: Copy inventory for Automation Platform
      when: 
        - aap_setup_single_node is defined
        - aap_setup_single_node
      ansible.builtin.template:
        src: inventory_container_single.j2
        dest: "/opt/ansible-automation-platform/installer/inventory"
        mode: "0755" 

- name: Configure SSL
  when: aap_configure_ssl
  block:
    - name: Copy CA and certs for SSL configuration
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/ansible-automation-platform/installer/{{ item }}
        mode: "0755"
      loop:
        - "{{ aap_ca_cert }}"
        - "{{ aap_ca_key }}"

- name: Configure SSL
  when:
    - aap_configure_ssl
    - aap_setup_rpm
  block:
    - name: Copy CA and certs for SSL configuration
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/ansible-automation-platform/installer/{{ item }}
        mode: "0755"
      loop:
        - "{{ aap_controller_cert }}"
        - "{{ aap_controller_key }}"
      when: controller_configure_ssl

    - name: Copy CA and certs for SSL configuration
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/ansible-automation-platform/installer/{{ item }}
        mode: "0755"
      loop:
        - "{{ aap_hub_cert }}"
        - "{{ aap_hub_key }}"
      when: hub_configure_ssl

    - name: Copy CA and certs for SSL configuration
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/ansible-automation-platform/installer/{{ item }}
        mode: "0755"
      loop:
        - "{{ aap_gw_cert }}"
        - "{{ aap_gw_key }}"
      when: gw_configure_ssl

    - name: Copy CA and certs for SSL configuration
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/ansible-automation-platform/installer/{{ item }}
        mode: "0755"
      loop:
        - "{{ aap_eda_cert }}"
        - "{{ aap_eda_key }}"
      when: eda_configure_ssl

- name: Configure Content Signing
  when: aap_configure_content_signing
  block:
    - name: Copy CA and certs for SSL configuration
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/ansible-automation-platform/installer/{{ item }}
        mode: "0755"
      loop:
        - "{{ aap_content_signing_key }}"
        - "{{ aap_content_signing_script }}"

- name: Install Automation Platform
  when: 
    - aap_setup_rpm is defined
    - aap_setup_rpm
  ansible.builtin.shell:
    cmd: ./setup.sh
    chdir: /opt/ansible-automation-platform/installer

- name: Install Automation Platform
  become: false
  when:
    - aap_setup_container is defined 
    - aap_setup_container
  ansible.builtin.shell:
    cmd: ansible-playbook -i inventory ansible.containerized_installer.install
    chdir: /opt/ansible-automation-platform/installer
